<?php
//
//This file is part of Ecoparc.
//
//Ecoparc is free software: you can redistribute it and/or modify
//it under the terms of the GNU General Public License as published by
//the Free Software Foundation, either version 3 of the License, or
//(at your option) any later version.
//
//Ecoparc is distributed in the hope that it will be useful,
//but WITHOUT ANY WARRANTY; without even the implied warranty of
//MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//GNU General Public License for more details.
//
//You should have received a copy of the GNU General Public License
//along with Ecoparc.  If not, see <http://www.gnu.org/licenses/>.
//
?>
<?php echo $this->render('header/int_header.phtml'); ?>
<div id="standard-content">
<div id="data-member">
    <?=$this->translate->_('welcome')?>
    <?php if ($this->waitingComputers == 1) { ?>
        <div class="message-info"><?=$this->translate->_('validation')?></div>
    <?php } else if ($this->waitingComputers > 1) { ?>
        <div class="message-info"><?=$this->translate->_('validations1').$this->waitingComputers.$this->translate->_('validations2')?></div>
    <?php } else { ?>
        <div class="message-info"><p></p></div>
    <?php } ?>
    <!--<?php echo "<br />".$this->translate->_('index_user')." : $this->username<br />".$this->translate->_('index_type')." : $this->type"?>-->
</div>
</div>
<?php echo $this->render('footer/int_footer.phtml'); ?>