<?php
//
//This file is part of Ecoparc.
//
//Ecoparc is free software: you can redistribute it and/or modify
//it under the terms of the GNU General Public License as published by
//the Free Software Foundation, either version 3 of the License, or
//(at your option) any later version.
//
//Ecoparc is distributed in the hope that it will be useful,
//but WITHOUT ANY WARRANTY; without even the implied warranty of
//MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//GNU General Public License for more details.
//
//You should have received a copy of the GNU General Public License
//along with Ecoparc.  If not, see <http://www.gnu.org/licenses/>.
//
?>
<?= $this->render('header/int_header.phtml'); ?>
<a href="<?php echo $this->url(array('controller'=>'users', 'action'=>'index'));?>"><?=$this->translate->_('retour')?></a>
    <?php
    if ($this->typeview == 1)
    {
        echo '<p>'.$this->translate->_('already_exist').'</p>';
    }
    else if ($this->typeview == 2)
    {
        ?>
        <p>
            <?php echo $this->translate->_('mod_valid'); ?>
        </p>
        <?php
    }
    else
        echo $this->form;
    ?>
<?= $this->render('footer/int_footer.phtml'); ?>
